### ISSUE TITLE
The API is not working after latest Google Chrome update

### ISSUE THREAD

**Issue by durakkerem** [googlearchive/webplatform-samples#14]
Hi, 
Although the live demo(https://www.google.com/intl/en/chrome/demos/speech.html) still works, on localhost and http server, I get the not-allowed error. Chrome won't allow the mic to record audio for the page. This happened on the latest version of Chrome. 

It still works in earlier versions.

**Comment by yizephyr** [comment]
The same happens to my case. Does that mean we must implement through https server?

**Comment by durakkerem** [comment]
Hello, I also found out that Chrome started to block permission requests from http thus allowing only https.   (though my localhost http server worked.)

I installed a self-signed certificate to my server and it's now working properly.

**Comment by yizephyr** [comment]
yup. The same way. It works now. :)
